name: Deploy to Dokku

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # ssh://dokku@dokku.host/app
          git_remote_url: ${{ secrets.DOKKU_SSH_URL }}
          branch: main
          git_push_flags: --force
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
